AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'Puppetfile'
    - 'modules/**/*'
    - 'spec/fixtures/**/*'

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  CountComments: false
  Max: 20
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
Style/FrozenStringLiteralComment:
  Enabled: false
